/**
 * File Description:
 * This file defines the root layout component for the API app's Next.js App Router tree.
 * It wraps every rendered route segment with the base HTML and body tags.
 *
 * Purpose:
 * The module exists to provide the required top-level document structure (`html` and `body`)
 * so all route content can be mounted consistently by Next.js.
 *
 * Key Responsibilities:
 * - Declare the root `RootLayout` component for the app.
 * - Provide the global HTML shell (`<html lang="en">` and `<body>`).
 * - Render nested route output via the `children` slot.
 */
/**
 * Renders the root document shell for the API app route tree.
 *
 * Purpose:
 * Provide a consistent top-level HTML/body wrapper so all nested route output
 * is rendered inside a valid document structure.
 *
 * Inputs:
 * - `children`: nested route/page content generated by Next.js.
 *
 * Output:
 * - Top-level HTML markup containing `children` inside `<body>`.
 */
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
